import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:warehouse_inventory/database/app_database.dart';
import 'package:warehouse_inventory/widgets/item_form_fields.dart';
import 'package:excel/excel.dart';
import 'package:share_plus/share_plus.dart';
import 'package:open_file/open_file.dart';
import 'package:permission_handler/permission_handler.dart';
import 'dart:io';
import 'dart:typed_data';
import 'package:path_provider/path_provider.dart';
import 'package:intl/intl.dart';

class AddInventoryItemScreen extends StatefulWidget {
  final Branch selectedBranch;

  const AddInventoryItemScreen({
    super.key,
    required this.selectedBranch,
  });

  @override
  State<AddInventoryItemScreen> createState() => _AddInventoryItemScreenState();
}

class _AddInventoryItemScreenState extends State<AddInventoryItemScreen> {
  final _formKey = GlobalKey<FormState>();
  final _skuController = TextEditingController();
  final _descriptionController = TextEditingController();
  final _quantityController = TextEditingController();
  final _locationController = TextEditingController();
  final _brandController = TextEditingController();
  bool _isLoading = false;
  bool _isExporting = false;
  List<MasterItem> _masterItems = [];
  MasterItem? _selectedMasterItem;

  Future<void> _saveItem() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() {
      _isLoading = true;
    });

    try {
      final sku = _skuController.text.trim();
      final branchId = widget.selectedBranch.id!;

      // Check if SKU already exists in this branch
      final skuExists = await AppDatabase.instance.checkSkuExistsInBranch(sku, branchId);
      if (skuExists) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('SKU "$sku" already exists in ${widget.selectedBranch.name}. Please use a different SKU.'),
              backgroundColor: Colors.red,
            ),
          );
        }
        return;
      }

      // Create InventoryItem using Drift-generated class
      final brandText = _brandController.text.trim();
      final item = InventoryItem(
        id: 0, // Will be auto-generated by database
        sku: sku,
        description: _descriptionController.text.trim(),
        end: int.parse(_quantityController.text.trim()),
        location: _locationController.text.trim(),
        brand: brandText.isEmpty ? null : brandText,
        dateAdded: DateTime.now().toIso8601String(),
        lastUpdated: null,
        branchId: branchId,
        beg: null,
        prev: null,
        sales: null,
      );

      await AppDatabase.instance.insertInventoryItem(item);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Inventory item added successfully!'),
            backgroundColor: Colors.green,
          ),
        );
        Navigator.pop(context);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error adding item: ${e.toString()}'),
            backgroundColor: Colors.red,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() {
          _isLoading = false;
        });
      }
    }
  }

  @override
  void initState() {
    super.initState();
    _loadMasterItems();
  }

  Future<void> _loadMasterItems() async {
    try {
      final items = await AppDatabase.instance.getMasterItemsByBranch(widget.selectedBranch.id!);
      setState(() {
        _masterItems = items;
      });
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error loading master items: ${e.toString()}'),
            backgroundColor: Colors.red,
          ),
        );
      }
    }
  }

  void _onMasterItemSelected(MasterItem? item) {
    setState(() {
      _selectedMasterItem = item;
      if (item != null) {
        _skuController.text = item.sku;
        _descriptionController.text = item.description;
        _locationController.text = item.location;
        _brandController.text = item.brand ?? '';
      } else {
        _skuController.clear();
        _descriptionController.clear();
        _locationController.clear();
        _brandController.clear();
      }
    });
  }

  Future<void> _exportToExcel() async {
    if (_isExporting) return;

    setState(() {
      _isExporting = true;
    });

    try {
      // Request storage permissions
      final status = await Permission.storage.request();
      if (!status.isGranted) {
        throw Exception('Storage permission is required to export inventory data.');
      }

      // Get all inventory items for this branch
      final inventoryItems = await AppDatabase.instance.getInventoryItemsByBranch(
        widget.selectedBranch.id!,
      );

      if (inventoryItems.isEmpty) {
        throw Exception('No inventory items found to export.');
      }

      // Create Excel workbook
      final excel = Excel.createExcel();
      final sheet = excel['Inventory'];

      // Add header row
      final headers = ['Item ID', 'Name', 'Beginning', 'Previous', 'Updated Quantity', 'End', 'Notes'];
      sheet.insertRowIterables(headers, 0);

      // Format header row
      for (int col = 0; col < headers.length; col++) {
        final cell = sheet.cell(CellIndex.indexByColumnRow(columnIndex: col, rowIndex: 0));
        cell.cellStyle = CellStyle(
          bold: true,
          fontSize: 12,
        );
      }

      // Add data rows
      for (int i = 0; i < inventoryItems.length; i++) {
        final item = inventoryItems[i];
        
        // Compute end quantity if not stored
        final beginning = item.beg ?? 0;
        final previous = item.prev ?? 0;
        final end = item.end;
        final updatedQuantity = item.sales ?? 0;
        final computedEnd = beginning + updatedQuantity;
        final finalEnd = end != null ? end : computedEnd;

        final rowData = [
          item.sku,
          item.description,
          beginning.toString(),
          previous.toString(),
          updatedQuantity.toString(),
          finalEnd.toString(),
          item.brand ?? '',
        ];

        sheet.insertRowIterables(rowData, i + 1);
      }

      // Generate filename with current timestamp
      final now = DateTime.now();
      final formatter = DateFormat('yyyyMMdd_HHmmss');
      final timestamp = formatter.format(now);
      final filename = 'inventory_${timestamp}.xlsx';

      // Save file
      final directory = await getExternalStorageDirectory();
      if (directory == null) {
        throw Exception('Could not access storage directory.');
      }

      final file = File('${directory.path}/$filename');
      final bytes = excel.encode();
      await file.writeAsBytes(bytes!);

      if (mounted) {
        // Show success message
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Excel file exported successfully: $filename'),
            backgroundColor: Colors.green,
            action: SnackBarAction(
              label: 'Open',
              textColor: Colors.white,
              onPressed: () => _openFile(file),
            ),
          ),
        );

        // Share the file
        await Share.shareXFiles(
          [XFile(file.path, mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')],
          subject: 'Inventory Export - ${widget.selectedBranch.name}',
          text: 'Inventory data exported from ${widget.selectedBranch.name}',
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error exporting Excel file: ${e.toString()}'),
            backgroundColor: Colors.red,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() {
          _isExporting = false;
        });
      }
    }
  }

  void _openFile(File file) async {
    try {
      await OpenFile.open(file.path);
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error opening file: ${e.toString()}'),
            backgroundColor: Colors.red,
          ),
        );
      }
    }
  }

  @override
  void dispose() {
    _skuController.dispose();
    _descriptionController.dispose();
    _quantityController.dispose();
    _locationController.dispose();
    _brandController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final screenWidth = MediaQuery.of(context).size.width;
    final isSmallScreen = screenWidth < 600;

    return Scaffold(
      appBar: AppBar(
        title: Text('Add Item to ${widget.selectedBranch.name}'),
        elevation: 0,
        backgroundColor: Theme.of(context).colorScheme.primary,
        foregroundColor: Colors.white,
      ),
      body: SingleChildScrollView(
        padding: EdgeInsets.all(isSmallScreen ? 16.0 : 24.0),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              // Branch Information Card
              Card(
                elevation: 3,
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(12),
                ),
                color: Colors.blue.shade50,
                child: Padding(
                  padding: const EdgeInsets.all(16.0),
                  child: Row(
                    children: [
                      Container(
                        padding: const EdgeInsets.all(12),
                        decoration: BoxDecoration(
                          color: Colors.blue.shade100,
                          borderRadius: BorderRadius.circular(8),
                        ),
                        child: Icon(
                          Icons.store,
                          color: Colors.blue.shade700,
                          size: 28,
                        ),
                      ),
                      const SizedBox(width: 16),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            const Text(
                              'Selected Branch',
                              style: TextStyle(
                                fontWeight: FontWeight.bold,
                                fontSize: 12,
                                color: Colors.black54,
                              ),
                            ),
                            const SizedBox(height: 4),
                            Text(
                              widget.selectedBranch.name,
                              style: const TextStyle(
                                fontSize: 18,
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                            Text(
                              widget.selectedBranch.location,
                              style: TextStyle(
                                fontSize: 14,
                                color: Colors.grey[600],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              const SizedBox(height: 20),
              
              // Master Item Selection Section
              if (_masterItems.isNotEmpty) ...[
                Card(
                  elevation: 2,
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Padding(
                    padding: const EdgeInsets.all(16.0),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Row(
                          children: [
                            Icon(Icons.list_alt, color: Colors.green.shade700),
                            const SizedBox(width: 8),
                            const Text(
                              'Select from Master Items',
                              style: TextStyle(
                                fontSize: 16,
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                          ],
                        ),
                        const SizedBox(height: 4),
                        Text(
                          'Choose an existing item or enter manually',
                          style: TextStyle(
                            fontSize: 12,
                            color: Colors.grey[600],
                          ),
                        ),
                        const SizedBox(height: 16),
                        DropdownButtonFormField<MasterItem>(
                          initialValue: _selectedMasterItem,
                          decoration: InputDecoration(
                            labelText: 'Master Item',
                            prefixIcon: const Icon(Icons.inventory),
                            border: OutlineInputBorder(
                              borderRadius: BorderRadius.circular(8),
                            ),
                            filled: true,
                            fillColor: Colors.grey.shade50,
                          ),
                          menuMaxHeight: 300,
                          isExpanded: true,
                          items: _masterItems.map((MasterItem item) {
                            return DropdownMenuItem<MasterItem>(
                              value: item,
                              child: Padding(
                                padding: const EdgeInsets.symmetric(vertical: 8.0),
                                child: Column(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  mainAxisSize: MainAxisSize.min,
                                  children: [
                                    Text(
                                      'SKU: ${item.sku}',
                                      style: const TextStyle(
                                        fontWeight: FontWeight.bold,
                                        fontSize: 14,
                                      ),
                                      overflow: TextOverflow.ellipsis,
                                      maxLines: 1,
                                    ),
                                    const SizedBox(height: 4),
                                    Text(
                                      item.description,
                                      style: const TextStyle(fontSize: 13),
                                      overflow: TextOverflow.ellipsis,
                                      maxLines: 1,
                                    ),
                                    const SizedBox(height: 2),
                                    if (item.brand != null && item.brand!.isNotEmpty) ...[
                                      Flexible(
                                        child: Text(
                                          'Brand: ${item.brand}',
                                          style: TextStyle(
                                            fontSize: 12,
                                            color: Colors.grey[700],
                                          ),
                                          overflow: TextOverflow.ellipsis,
                                          maxLines: 1,
                                        ),
                                      ),
                                    ],
                                  ],
                                ),
                              ),
                            );
                          }).toList(),
                          onChanged: _onMasterItemSelected,
                          validator: (value) {
                            if (value == null && _masterItems.isNotEmpty) {
                              return 'Please select a master item or enter details manually';
                            }
                            return null;
                          },
                        ),
                      ],
                    ),
                  ),
                ),
                const SizedBox(height: 20),
              ],
              
              // Item Details Section
              Card(
                elevation: 3,
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(12),
                ),
                child: Padding(
                  padding: const EdgeInsets.all(20.0),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Row(
                        children: [
                          Icon(Icons.edit_note, color: Colors.orange.shade700),
                          const SizedBox(width: 8),
                          const Text(
                            'Item Details',
                            style: TextStyle(
                              fontSize: 18,
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                        ],
                      ),
                      const Divider(height: 24),
                      ItemFormFields(
                        skuController: _skuController,
                        descriptionController: _descriptionController,
                        brandController: _brandController,
                        quantityController: _quantityController,
                        isReadonly: _selectedMasterItem != null,
                        skuValidator: (value) {
                          if (value == null || value.trim().isEmpty) {
                            return 'Please enter SKU';
                          }
                          return null;
                        },
                        descriptionValidator: (value) {
                          if (value == null || value.trim().isEmpty) {
                            return 'Please enter description';
                          }
                          return null;
                        },
                        brandValidator: (value) {
                          return null; // Brand is optional
                        },
                        quantityValidator: (value) {
                          if (value == null || value.trim().isEmpty) {
                            return 'Please enter quantity';
                          }
                          if (int.tryParse(value.trim()) == null || int.parse(value.trim()) < 0) {
                            return 'Please enter a valid positive number';
                          }
                          return null;
                        },
                        quantityInputFormatters: [FilteringTextInputFormatter.digitsOnly],
                      ),
                      const SizedBox(height: 16),
                      TextFormField(
                        controller: _locationController,
                        decoration: InputDecoration(
                          labelText: 'Location *',
                          prefixIcon: const Icon(Icons.location_on),
                          border: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(8),
                          ),
                          filled: true,
                          fillColor: Colors.grey.shade50,
                        ),
                        readOnly: _selectedMasterItem != null,
                        validator: (value) {
                          if (value == null || value.trim().isEmpty) {
                            return 'Please enter location';
                          }
                          return null;
                        },
                      ),
                    ],
                  ),
                ),
              ),
              const SizedBox(height: 24),
              
              // Submit Button
              ElevatedButton.icon(
                onPressed: _isLoading ? null : _saveItem,
                style: ElevatedButton.styleFrom(
                  padding: const EdgeInsets.symmetric(vertical: 16),
                  backgroundColor: Colors.green.shade600,
                  foregroundColor: Colors.white,
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(12),
                  ),
                  elevation: 2,
                ),
                icon: _isLoading
                    ? const SizedBox(
                        width: 20,
                        height: 20,
                        child: CircularProgressIndicator(
                          color: Colors.white,
                          strokeWidth: 2,
                        ),
                      )
                    : const Icon(Icons.add_circle),
                label: Text(
                  _isLoading ? 'Adding Item...' : 'Add Item to Inventory',
                  style: const TextStyle(
                    fontSize: 16,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: _isExporting ? null : _exportToExcel,
        backgroundColor: _isExporting ? Colors.grey : Colors.blue,
        foregroundColor: Colors.white,
        icon: _isExporting
            ? const SizedBox(
                width: 20,
                height: 20,
                child: CircularProgressIndicator(
                  color: Colors.white,
                  strokeWidth: 2,
                ),
              )
            : const Icon(Icons.download),
        label: Text(
          _isExporting ? 'Exporting...' : 'Export Excel',
          style: const TextStyle(fontWeight: FontWeight.bold),
        ),
        tooltip: 'Export inventory to Excel',
      ),
    );
  }
}